//! The per-provider canonical-feature support matrix (FRD-018 Part III M1).
//!
//! Every provider's `from_standard(&StandardSTTConfig) -> Self` is **infallible**: it reads the
//! fields it can map and never records the ones it cannot. So before this module, WaaV could not
//! answer "does deepgram honour `sentiment`?" at all — and offering `sentiment` on every voice
//! deployment means it silently does nothing on most of them. That is why the matrix is a
//! prerequisite for exposing the canonical vocabulary rather than a follow-up: shipping the
//! vocabulary without it moves the silence from the API into the UI.
//!
//! **The matrix is derived, not asserted.** A provider "supports" a canonical feature exactly
//! when its mapping *reads that field*, and the guard test below recomputes the whole table from
//! the provider sources and refuses to pass unless it matches. Delete a read from a
//! `from_standard` and this goes red; add one and it goes red until the table is updated. A
//! hand-maintained table would be a second thing that can lie about the same question, which is
//! the defect the matrix exists to fix.
//!
//! Two families already had a real declaration and are unchanged: emotion, through
//! `ProviderEmotionSupport`, and language, through the per-vendor mappers exposed at
//! `GET /capabilities/languages`. This is the same idea for the rest of the vocabulary, exposed
//! the same way, at `GET /capabilities/features`.

use serde::Serialize;

/// One provider's honoured canonical features.
#[derive(Debug, Clone, Serialize)]
pub struct FeatureSupport {
    /// The provider id a `voice_table` entry names, and the first alias of its dispatch arm.
    pub provider: &'static str,
    /// The source module the mapping lives in. Carried so the guard can find the code it checks
    /// the claim against; a matrix that could not be traced back to a file would be unverifiable.
    #[serde(skip)]
    pub module: &'static str,
    /// The `core::stt::batch` builder that serves this vendor's PRERECORDED uploads, if it has
    /// one.
    ///
    /// A vendor reachable over two transports has two mappings, and a deployment's settings
    /// configure the prerecorded one — so the row is the UNION of what both read. It matters
    /// because the batch wire deliberately re-enables features the streaming mapper drops:
    /// `sentiment` for Deepgram, `profanity_filter` / `redaction` / `multichannel` for
    /// AssemblyAI. Without this the matrix would hide controls that now work.
    ///
    /// `None` for the 27 vendors served only by their streaming client, and for OpenAI, whose
    /// single client already IS the prerecorded API.
    #[serde(skip)]
    pub batch_builder: Option<&'static str>,
    /// Canonical field names from `SttFeatures` / `TtsFeatures` that this provider's mapping reads.
    pub features: &'static [&'static str],
}

impl FeatureSupport {
    pub fn honours(&self, feature: &str) -> bool {
        self.features.contains(&feature)
    }
}

/// Every canonical `SttFeatures` field, in declaration order.
pub const STT_FEATURE_VOCABULARY: &[&str] = &[
    "interim_results",
    "diarization",
    "word_timestamps",
    "smart_format",
    "profanity_filter",
    "filler_words",
    "vad_events",
    "endpointing_ms",
    "utterance_end_ms",
    "keyterms",
    "redaction",
    "language_detection",
    "entity_detection",
    "numerals",
    "multichannel",
    "alternatives",
    "sentiment",
    "speech_begin_event",
];

/// Every canonical `TtsFeatures` field, in declaration order.
pub const TTS_FEATURE_VOCABULARY: &[&str] = &[
    "speed",
    "pitch",
    "volume",
    "stability",
    "similarity_boost",
    "style",
    "use_speaker_boost",
    "emotion",
    "instructions",
    "ssml",
    "language",
    "word_timestamps",
    "streaming",
    "seed",
    "sample_rate",
    "optimize_streaming_latency",
    "include_timestamp_types",
    "rate_percentage",
    "pitch_percentage",
];

/// The STT matrix. Regenerated by the guard test; do not edit by hand.
pub const STT_FEATURE_SUPPORT: &[FeatureSupport] = &[
    FeatureSupport {
        provider: "alibaba-cloud",
        module: "alibaba_cloud",
        batch_builder: None,
        features: &["filler_words", "endpointing_ms", "language_detection"],
    },
    FeatureSupport {
        provider: "amivoice",
        module: "amivoice",
        batch_builder: None,
        features: &["interim_results", "diarization", "filler_words"],
    },
    FeatureSupport {
        provider: "assemblyai",
        module: "assemblyai",
        batch_builder: Some("build_assemblyai_transcript"),
        // The last three reach only the PRERECORDED wire — AssemblyAI's v3 streaming socket has
        // no equivalent, which is exactly why the upload route now uses the batch API.
        features: &[
            "diarization",
            "word_timestamps",
            "endpointing_ms",
            "keyterms",
            "language_detection",
            "entity_detection",
            "sentiment",
            "multichannel",
            "profanity_filter",
            "redaction",
        ],
    },
    FeatureSupport {
        provider: "aws-transcribe",
        module: "aws_transcribe",
        batch_builder: None,
        features: &["interim_results", "diarization", "redaction"],
    },
    FeatureSupport {
        provider: "azure",
        module: "azure",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "word_timestamps",
            "profanity_filter",
            "filler_words",
            "endpointing_ms",
            "keyterms",
            "language_detection",
            "alternatives",
            "sentiment",
        ],
    },
    FeatureSupport {
        provider: "baidu",
        module: "baidu",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "bhashini",
        module: "bhashini",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "cartesia",
        module: "cartesia",
        batch_builder: None,
        features: &["endpointing_ms"],
    },
    FeatureSupport {
        provider: "deepgram",
        module: "deepgram",
        batch_builder: Some("build_deepgram_prerecorded_with"),
        // `sentiment` is prerecorded-only on Deepgram; the streaming mapper drops it. The
        // streaming-only entries here (`interim_results`, `vad_events`, endpointing) are still
        // true of a live session, and budapp gates them out of a deployment's batch config
        // separately — see its STT_STREAMING_ONLY_FEATURES.
        features: &[
            "sentiment",
            "interim_results",
            "diarization",
            "smart_format",
            "profanity_filter",
            "filler_words",
            "vad_events",
            "endpointing_ms",
            "utterance_end_ms",
            "keyterms",
            "redaction",
            "language_detection",
            "entity_detection",
            "numerals",
            "multichannel",
            "alternatives",
        ],
    },
    // ElevenLabs is the one vendor with TWO mappings in its module: the realtime WebSocket client
    // and the batch `POST /v1/speech-to-text` client. The row is their union, and it is unchanged
    // by the batch client because the batch API's extra reach is in knobs the canonical
    // vocabulary has no name for (`tag_audio_events`, `num_speakers`, `temperature`, `seed`,
    // speaker roles), which travel through `extras`. The one canonical feature batch could add —
    // `multichannel` — is deliberately not mapped: this transport decodes every upload to mono,
    // so it would be a control that can never do anything. See `elevenlabs::batch`.
    FeatureSupport {
        provider: "elevenlabs",
        module: "elevenlabs",
        batch_builder: Some("build_elevenlabs_transcription_with"),
        features: &[
            "diarization",
            "word_timestamps",
            "filler_words",
            "keyterms",
            "redaction",
            "language_detection",
            "entity_detection",
        ],
    },
    FeatureSupport {
        provider: "fpt-ai",
        module: "fpt_ai",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "gladia",
        module: "gladia",
        batch_builder: None,
        features: &[
            "interim_results",
            "word_timestamps",
            "keyterms",
            "language_detection",
            "entity_detection",
        ],
    },
    FeatureSupport {
        provider: "gnani",
        module: "gnani",
        batch_builder: None,
        features: &["interim_results"],
    },
    FeatureSupport {
        provider: "google",
        module: "google",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "word_timestamps",
            "profanity_filter",
            "vad_events",
            "keyterms",
            "multichannel",
            "alternatives",
        ],
    },
    FeatureSupport {
        provider: "groq",
        module: "groq",
        batch_builder: None,
        features: &["word_timestamps"],
    },
    FeatureSupport {
        provider: "ibm-watson",
        module: "ibm_watson",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "word_timestamps",
            "smart_format",
            "profanity_filter",
            "keyterms",
            "redaction",
            "alternatives",
            "speech_begin_event",
        ],
    },
    FeatureSupport {
        provider: "iflytek",
        module: "iflytek",
        batch_builder: None,
        features: &[
            "word_timestamps",
            "smart_format",
            "endpointing_ms",
            "alternatives",
        ],
    },
    FeatureSupport {
        provider: "naver-clova",
        module: "naver_clova",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "nectec",
        module: "nectec",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "openai",
        module: "openai",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "word_timestamps",
            "keyterms",
        ],
    },
    FeatureSupport {
        provider: "phonexia",
        module: "phonexia",
        batch_builder: None,
        features: &["word_timestamps", "keyterms"],
    },
    FeatureSupport {
        provider: "revai",
        module: "revai",
        batch_builder: None,
        features: &["diarization", "profanity_filter", "filler_words"],
    },
    FeatureSupport {
        provider: "reverie",
        module: "reverie",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "sarvam",
        module: "sarvam",
        batch_builder: None,
        features: &["vad_events"],
    },
    FeatureSupport {
        provider: "sberdevices",
        module: "sberdevices",
        batch_builder: None,
        features: &["profanity_filter", "multichannel"],
    },
    FeatureSupport {
        provider: "speechmatics",
        module: "speechmatics",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "filler_words",
            "utterance_end_ms",
            "keyterms",
            "entity_detection",
            "multichannel",
        ],
    },
    FeatureSupport {
        provider: "tencent",
        module: "tencent",
        batch_builder: None,
        features: &[
            "word_timestamps",
            "profanity_filter",
            "filler_words",
            "vad_events",
            "endpointing_ms",
            "keyterms",
        ],
    },
    FeatureSupport {
        provider: "tinkoff",
        module: "tinkoff",
        batch_builder: None,
        features: &[
            "interim_results",
            "profanity_filter",
            "keyterms",
            "numerals",
        ],
    },
    FeatureSupport {
        provider: "viettel-ai",
        module: "viettel_ai",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "yandex",
        module: "yandex",
        batch_builder: None,
        features: &[
            "interim_results",
            "diarization",
            "profanity_filter",
            "keyterms",
            "numerals",
        ],
    },
];

/// The TTS matrix. Regenerated by the guard test; do not edit by hand.
pub const TTS_FEATURE_SUPPORT: &[FeatureSupport] = &[
    FeatureSupport {
        provider: "acapela",
        module: "acapela",
        batch_builder: None,
        features: &["speed", "volume", "ssml", "word_timestamps", "sample_rate"],
    },
    FeatureSupport {
        provider: "alibaba_cloud",
        module: "alibaba_cloud",
        batch_builder: None,
        features: &[
            "speed",
            "pitch",
            "volume",
            "instructions",
            "ssml",
            "language",
            "word_timestamps",
            "seed",
            "sample_rate",
        ],
    },
    FeatureSupport {
        provider: "aws_polly",
        module: "aws_polly",
        batch_builder: None,
        features: &["ssml", "language", "sample_rate"],
    },
    FeatureSupport {
        provider: "azure",
        module: "azure",
        batch_builder: None,
        features: &["speed", "pitch", "volume", "emotion", "ssml", "language"],
    },
    FeatureSupport {
        provider: "baidu",
        module: "baidu",
        batch_builder: None,
        features: &["speed", "pitch", "volume"],
    },
    FeatureSupport {
        provider: "bhashini",
        module: "bhashini",
        batch_builder: None,
        features: &["language", "sample_rate"],
    },
    FeatureSupport {
        provider: "cartesia",
        module: "cartesia",
        batch_builder: None,
        features: &["speed", "volume", "emotion", "language", "sample_rate"],
    },
    FeatureSupport {
        provider: "cereproc",
        module: "cereproc",
        batch_builder: None,
        features: &["emotion", "language", "streaming", "sample_rate"],
    },
    FeatureSupport {
        provider: "deepgram",
        module: "deepgram_aura",
        batch_builder: None,
        features: &["streaming", "sample_rate"],
    },
    FeatureSupport {
        provider: "elevenlabs",
        module: "elevenlabs",
        batch_builder: None,
        features: &[
            "speed",
            "stability",
            "similarity_boost",
            "style",
            "use_speaker_boost",
            "language",
            "seed",
            "sample_rate",
            "optimize_streaming_latency",
        ],
    },
    FeatureSupport {
        provider: "fpt_ai",
        module: "fpt_ai",
        batch_builder: None,
        features: &["speed"],
    },
    FeatureSupport {
        provider: "gnani",
        module: "gnani",
        batch_builder: None,
        features: &["language", "sample_rate"],
    },
    FeatureSupport {
        provider: "google",
        module: "google",
        batch_builder: None,
        features: &[
            "speed",
            "pitch",
            "volume",
            "instructions",
            "ssml",
            "language",
            "sample_rate",
        ],
    },
    FeatureSupport {
        provider: "huawei_cloud",
        module: "huawei_cloud",
        batch_builder: None,
        features: &["speed", "pitch", "volume", "word_timestamps", "sample_rate"],
    },
    FeatureSupport {
        provider: "hume",
        module: "hume",
        batch_builder: None,
        features: &[
            "speed",
            "emotion",
            "instructions",
            "sample_rate",
            "include_timestamp_types",
        ],
    },
    FeatureSupport {
        provider: "ibm_watson",
        module: "ibm_watson",
        batch_builder: None,
        features: &[
            "speed",
            "pitch",
            "sample_rate",
            "rate_percentage",
            "pitch_percentage",
        ],
    },
    FeatureSupport {
        provider: "iflytek",
        module: "iflytek",
        batch_builder: None,
        features: &["speed", "pitch", "volume", "sample_rate"],
    },
    FeatureSupport {
        provider: "murf",
        module: "murf",
        batch_builder: None,
        features: &["speed", "pitch", "emotion", "language", "sample_rate"],
    },
    FeatureSupport {
        provider: "naver_clova",
        module: "naver_clova",
        batch_builder: None,
        features: &["speed", "pitch", "volume", "sample_rate"],
    },
    FeatureSupport {
        provider: "nectec",
        module: "nectec",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "openai",
        module: "openai",
        batch_builder: None,
        features: &["speed", "instructions"],
    },
    FeatureSupport {
        provider: "resemble",
        module: "resemble",
        batch_builder: None,
        features: &["sample_rate"],
    },
    FeatureSupport {
        provider: "reverie",
        module: "reverie",
        batch_builder: None,
        features: &["speed", "pitch", "ssml", "language", "sample_rate"],
    },
    FeatureSupport {
        provider: "sberdevices",
        module: "sberdevices",
        batch_builder: None,
        features: &["ssml", "sample_rate"],
    },
    FeatureSupport {
        provider: "smallest",
        module: "smallest",
        batch_builder: None,
        features: &["speed", "stability", "similarity_boost", "sample_rate"],
    },
    FeatureSupport {
        provider: "speechify",
        module: "speechify",
        batch_builder: None,
        features: &["language"],
    },
    FeatureSupport {
        provider: "speechmatics",
        module: "speechmatics",
        batch_builder: None,
        features: &[],
    },
    FeatureSupport {
        provider: "tencent",
        module: "tencent",
        batch_builder: None,
        features: &["speed", "volume", "emotion", "word_timestamps"],
    },
    FeatureSupport {
        provider: "tinkoff",
        module: "tinkoff",
        batch_builder: None,
        features: &["speed", "pitch", "volume", "ssml", "sample_rate"],
    },
    FeatureSupport {
        provider: "unrealspeech",
        module: "unrealspeech",
        batch_builder: None,
        features: &["speed", "pitch"],
    },
    FeatureSupport {
        provider: "viettel_ai",
        module: "viettel_ai",
        batch_builder: None,
        features: &["speed"],
    },
    FeatureSupport {
        provider: "wellsaid",
        module: "wellsaid",
        batch_builder: None,
        features: &["ssml", "sample_rate"],
    },
    FeatureSupport {
        provider: "yandex",
        module: "yandex",
        batch_builder: None,
        features: &["speed", "emotion", "ssml", "language", "sample_rate"],
    },
    FeatureSupport {
        provider: "zalo_ai",
        module: "zalo_ai",
        batch_builder: None,
        features: &["speed"],
    },
];

/// Find a provider's row, treating `-` and `_` as the same separator.
///
/// They are not meaningful, and the two vocabularies disagree about them: budapp's `voice_table`
/// spells nine vendors with a hyphen (`aws-polly`, `ibm-watson`, `alibaba-cloud`, …) while the TTS
/// table — derived from module directory names — spells them with an underscore. The STT table
/// uses hyphens, because its rows are named after dispatch aliases rather than modules.
///
/// An exact match therefore found NO row for those nine on the TTS side, so `tts_honours` fell
/// through to "assume capable" and **no advisory was ever emitted for any of them** — the
/// silence this matrix exists to remove, reintroduced by a punctuation mismatch.
fn find<'a>(rows: &'a [FeatureSupport], provider: &str) -> Option<&'a FeatureSupport> {
    let key = normalize_provider(provider);
    rows.iter().find(|r| normalize_provider(r.provider) == key)
}

/// A provider id with its separator and case flattened, for matching only.
pub(crate) fn normalize_provider(provider: &str) -> String {
    provider.trim().to_lowercase().replace('-', "_")
}

/// Whether a provider's STT mapping honours a canonical feature.
///
/// An UNKNOWN provider answers `true`. That is deliberate: the matrix covers the providers
/// reachable through `create_stt_standard`, and answering `false` for one it does not cover
/// would turn "we have not catalogued this vendor" into "this vendor does not support it" — a
/// warning for something that works, which teaches a caller to ignore warnings.
pub fn stt_honours(provider: &str, feature: &str) -> bool {
    find(STT_FEATURE_SUPPORT, provider).is_none_or(|row| row.honours(feature))
}

/// Whether a provider's TTS mapping honours a canonical feature. Unknown providers answer `true`,
/// for the reason given on [`stt_honours`].
pub fn tts_honours(provider: &str, feature: &str) -> bool {
    find(TTS_FEATURE_SUPPORT, provider).is_none_or(|row| row.honours(feature))
}

/// The `/capabilities/features` payload.
#[derive(Debug, Clone, Serialize)]
pub struct FeatureCapabilitiesResponse {
    /// Every canonical STT feature a caller may configure.
    pub stt_vocabulary: &'static [&'static str],
    /// Every canonical TTS feature a caller may configure.
    pub tts_vocabulary: &'static [&'static str],
    /// Which providers honour which STT features.
    pub stt: &'static [FeatureSupport],
    /// Which providers honour which TTS features.
    pub tts: &'static [FeatureSupport],
    /// The five STT features that need a continuous stream, named so a UI can explain their
    /// absence rather than silently omitting them.
    pub streaming_only: &'static [&'static str],
    /// Which emotions each TTS vendor honours, and whether intensity and delivery style reach it.
    ///
    /// `tts` above answers "does this vendor read the `emotion` field at all"; this answers
    /// "which of the 44 canonical emotions does it do anything with", which is a different
    /// question and the one a settings form needs. Three vendors are narrower than the canonical
    /// list — ElevenLabs honours 8, Azure 10, Cartesia 33 — so a form built on `tts` alone offers
    /// up to 36 emotions that reach the vendor and change nothing.
    pub emotions: Vec<crate::core::emotion::matrix::EmotionSupportRow>,
    /// Which vendors can translate, and in what sense.
    ///
    /// Five of thirty-one, in three different ways — arbitrary targets, English-only, and
    /// batch-only. `stt` above says nothing about it, so a form built on that alone offered
    /// "Target languages" to twenty-six vendors that cannot translate at all, where setting it
    /// changed nothing about the request and reported nothing back.
    pub translation: Vec<crate::core::stt::translation_matrix::TranslationSupportRow>,
}

/// The five canonical STT features that have no meaning on a prerecorded upload.
pub const STREAMING_ONLY_STT_FEATURES: &[&str] = &[
    "interim_results",
    "vad_events",
    "endpointing_ms",
    "utterance_end_ms",
    "speech_begin_event",
];

pub fn feature_capabilities() -> FeatureCapabilitiesResponse {
    FeatureCapabilitiesResponse {
        stt_vocabulary: STT_FEATURE_VOCABULARY,
        tts_vocabulary: TTS_FEATURE_VOCABULARY,
        stt: STT_FEATURE_SUPPORT,
        tts: TTS_FEATURE_SUPPORT,
        streaming_only: STREAMING_ONLY_STT_FEATURES,
        emotions: crate::core::emotion::matrix::emotion_support_matrix(),
        translation: crate::core::stt::translation_matrix::translation_support_matrix(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;
    use std::path::PathBuf;

    fn core_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/core")
    }

    /// Everything before the first `#[cfg(test)]`.
    ///
    /// A field named only inside a test is not a mapping, and counting one would let a provider
    /// claim a feature it merely has a fixture for.
    fn without_tests(src: &str) -> String {
        match src.find("#[cfg(test)]") {
            Some(i) => src[..i].to_string(),
            None => src.to_string(),
        }
    }

    /// Every non-test source file belonging to a provider module.
    ///
    /// Directory-wide, because the mapping does not always live in `mod.rs` — assemblyai keeps
    /// it in `config.rs`, and a scan that only read the module root reported an empty row for
    /// nine providers that map plenty.
    fn provider_source(kind: &str, module: &str) -> String {
        let base = core_dir().join(kind);
        let single = base.join(format!("{module}.rs"));
        if single.is_file() {
            return without_tests(&std::fs::read_to_string(&single).unwrap());
        }
        let dir = base.join(module);
        let mut out = String::new();
        let mut stack = vec![dir];
        while let Some(d) = stack.pop() {
            let Ok(entries) = std::fs::read_dir(&d) else {
                continue;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "rs")
                    && path.file_name().is_some_and(|n| n != "tests.rs")
                {
                    out.push_str(&without_tests(&std::fs::read_to_string(&path).unwrap()));
                    out.push('\n');
                }
            }
        }
        out
    }

    /// Which canonical fields this module's source actually reads off `features`.
    ///
    /// The bindings are what the mappings use: `let f = &std.features;` is the dominant idiom,
    /// with a handful of `feats` / `ft` / direct `std.features.x` spellings. A new binding name
    /// shows up as a provider that suddenly claims nothing, which is a loud failure, not a quiet
    /// one — the row would have to be emptied for the test to pass again.
    fn features_read(source: &str, vocabulary: &[&str]) -> BTreeSet<String> {
        const BINDINGS: &[&str] = &[
            "f.",
            "ft.",
            "feat.",
            "feats.",
            "features.",
            "std.features.",
            "config.features.",
        ];
        let mut found = BTreeSet::new();
        for field in vocabulary {
            for binding in BINDINGS {
                let needle = format!("{binding}{field}");
                if source.match_indices(&needle).any(|(i, _)| {
                    // Reject a longer field name ending in this one: `.pitch` must not match
                    // `.pitch_percentage`, or every provider mapping the latter would claim both.
                    let after = source[i + needle.len()..].chars().next();
                    let before = source[..i].chars().next_back();
                    !after.is_some_and(|c| c.is_alphanumeric() || c == '_')
                        && !before.is_some_and(|c| c.is_alphanumeric() || c == '_' || c == '.')
                }) {
                    found.insert((*field).to_string());
                    break;
                }
            }
        }
        found
    }

    /// The body of one `pub fn <name>(...)` in `core/stt/batch.rs`.
    ///
    /// Scoped to the single function rather than the whole file, because every vendor's builder
    /// lives there: reading the file whole would have each of them claim every feature any of
    /// them maps, which is a matrix that cannot be wrong and therefore cannot be useful.
    fn batch_builder_source(name: &str) -> String {
        let src = std::fs::read_to_string(core_dir().join("stt/batch.rs")).unwrap();
        let src = without_tests(&src);
        let start = src
            .find(&format!("pub fn {name}("))
            .unwrap_or_else(|| panic!("no `pub fn {name}` in core/stt/batch.rs"));
        // Builders end at the next top-level item; `\n}\n` is the closing brace of the function.
        let rest = &src[start..];
        let end = rest.find("\n}\n").map(|i| i + 2).unwrap_or(rest.len());
        rest[..end].to_string()
    }

    fn check(rows: &[FeatureSupport], kind: &str, vocabulary: &[&str]) {
        let mut drifted = Vec::new();
        for row in rows {
            let mut actual = features_read(&provider_source(kind, row.module), vocabulary);
            // A vendor reachable over two transports has two mappings. The union is what a
            // deployment can configure, because the prerecorded builder is what an upload runs.
            if let Some(builder) = row.batch_builder {
                actual.extend(features_read(&batch_builder_source(builder), vocabulary));
            }
            let claimed: BTreeSet<String> = row.features.iter().map(|f| (*f).to_string()).collect();
            if actual != claimed {
                let over: Vec<_> = claimed.difference(&actual).cloned().collect();
                let under: Vec<_> = actual.difference(&claimed).cloned().collect();
                drifted.push(format!(
                    "{}/{}: claims-but-does-not-read {:?}, reads-but-does-not-claim {:?}",
                    kind, row.provider, over, under
                ));
            }
        }
        assert!(
            drifted.is_empty(),
            "the feature matrix no longer matches the mappings it describes:\n  {}",
            drifted.join("\n  ")
        );
    }

    /// TC-REQ-06. Delete a feature read from a provider's `from_standard` and this goes red.
    ///
    /// This is the whole point of the matrix. A declaration that stays green when the mapping it
    /// describes is removed is a second source of silent drift, which is the defect it was built
    /// to fix.
    #[test]
    fn the_stt_matrix_cannot_lie_about_a_mapping() {
        check(STT_FEATURE_SUPPORT, "stt", STT_FEATURE_VOCABULARY);
    }

    #[test]
    fn the_tts_matrix_cannot_lie_about_a_mapping() {
        check(TTS_FEATURE_SUPPORT, "tts", TTS_FEATURE_VOCABULARY);
    }

    #[test]
    fn a_field_name_is_not_matched_by_a_longer_one() {
        // `pitch` and `pitch_percentage` are separate knobs on separate vendors, and a prefix
        // match would have every IBM Watson row claim both.
        let source = "cfg.rate = ft.pitch_percentage.unwrap_or(0);";
        let found = features_read(source, &["pitch", "pitch_percentage"]);
        assert_eq!(found.len(), 1);
        assert!(found.contains("pitch_percentage"));
    }

    #[test]
    fn a_test_only_mention_is_not_a_mapping() {
        let src = "fn map(f: &X) { let _ = f.diarization; }\n#[cfg(test)]\nmod t { let _ = f.sentiment; }";
        let found = features_read(&without_tests(src), STT_FEATURE_VOCABULARY);
        assert!(found.contains("diarization"));
        assert!(!found.contains("sentiment"), "a fixture is not a mapping");
    }

    #[test]
    fn a_vendor_spelled_with_the_other_separator_still_resolves() {
        // The defect: budapp's `voice_table` says `aws-polly`, this table says `aws_polly`, and
        // an exact match found nothing — so `tts_honours` answered "assume capable" and NO
        // advisory was ever emitted for nine real TTS vendors. The matrix was not wrong; it was
        // unreachable.
        for (budapp_spelling, table_spelling) in [
            ("aws-polly", "aws_polly"),
            ("ibm-watson", "ibm_watson"),
            ("alibaba-cloud", "alibaba_cloud"),
            ("naver-clova", "naver_clova"),
            ("huawei-cloud", "huawei_cloud"),
        ] {
            let by_budapp = find(TTS_FEATURE_SUPPORT, budapp_spelling);
            let by_table = find(TTS_FEATURE_SUPPORT, table_spelling);
            assert!(
                by_budapp.is_some(),
                "{budapp_spelling} does not resolve; every advisory for it is silently skipped"
            );
            assert_eq!(
                by_budapp.map(|r| r.provider),
                by_table.map(|r| r.provider),
                "{budapp_spelling} and {table_spelling} must be the same vendor"
            );
        }
        // The STT table spells them the other way round, and must keep working.
        assert!(find(STT_FEATURE_SUPPORT, "ibm-watson").is_some());
        assert!(find(STT_FEATURE_SUPPORT, "ibm_watson").is_some());
    }

    #[test]
    fn no_two_rows_collide_once_separators_are_flattened() {
        // Normalizing for the lookup is only safe while it cannot make two vendors the same one.
        for (kind, rows) in [("stt", STT_FEATURE_SUPPORT), ("tts", TTS_FEATURE_SUPPORT)] {
            let mut seen = BTreeSet::new();
            for row in rows {
                assert!(
                    seen.insert(normalize_provider(row.provider)),
                    "{kind}: {} collides with another row once `-` and `_` are flattened",
                    row.provider
                );
            }
        }
    }

    #[test]
    fn an_uncatalogued_provider_is_assumed_capable() {
        // Answering `false` would turn "not catalogued" into "not supported" and warn about
        // something that works. A caller who learns to ignore warnings has lost the channel.
        assert!(stt_honours("a-vendor-added-last-week", "diarization"));
        assert!(tts_honours("a-vendor-added-last-week", "emotion"));
    }

    #[test]
    fn a_catalogued_provider_answers_from_its_row() {
        assert!(stt_honours("deepgram", "diarization"));
        assert!(!stt_honours("groq", "diarization"));
        assert!(tts_honours("elevenlabs", "use_speaker_boost"));
        assert!(!tts_honours("deepgram", "use_speaker_boost"));
    }

    #[test]
    fn the_matrix_covers_the_providers_the_dispatch_can_construct() {
        // A row per dispatch arm. If `create_stt_standard` gains a provider and the matrix does
        // not, that vendor silently falls into the assume-capable branch above and every
        // advisory for it disappears.
        let stt = std::fs::read_to_string(core_dir().join("stt/standard.rs")).unwrap();
        let dispatch = &stt[stt.find("pub fn create_stt_standard(").unwrap()..];
        for row in STT_FEATURE_SUPPORT {
            assert!(
                dispatch.contains(&format!("super::{}::", row.module)),
                "stt matrix names {} but create_stt_standard cannot construct it",
                row.provider
            );
        }
    }
}
