/**
 * WaaV CLI Shell Completion Scripts
 *
 * Generates shell completion scripts for bash, zsh, and fish.
 */

import { logger } from '../utils/logger.js';
import type { GlobalOptions } from '../cli.js';

type Shell = 'bash' | 'zsh' | 'fish' | 'powershell';

/**
 * All commands and their descriptions
 */
const COMMANDS = {
  init: 'First-time setup wizard',
  config: 'Configuration management',
  'config show': 'Display current configuration',
  'config set': 'Set configuration value',
  'config edit': 'Open config in editor',
  'config reset': 'Reset to defaults',
  provider: 'Provider management',
  'provider list': 'List all providers',
  'provider add': 'Add/configure a provider',
  'provider test': 'Test provider connectivity',
  'provider browse': 'Interactive provider browser',
  'provider remove': 'Remove provider configuration',
  dag: 'DAG pipeline management',
  'dag list': 'List saved DAG pipelines',
  'dag create': 'Create new DAG pipeline',
  'dag validate': 'Validate DAG configuration',
  'dag visualize': 'ASCII visualization of DAG',
  'dag edit': 'Edit existing DAG',
  server: 'Gateway server control',
  'server start': 'Start the gateway server',
  'server stop': 'Stop the gateway server',
  'server restart': 'Restart the gateway server',
  'server status': 'Show server status',
  'server logs': 'Tail server logs',
  voice: 'Voice interaction mode',
  'voice start': 'Start voice conversation',
  'voice test': 'Test mic/speaker setup',
  'voice configure': 'Audio device configuration',
  dashboard: 'Interactive analytics dashboard',
  doctor: 'Diagnose issues',
  completion: 'Generate shell completions',
};

/**
 * Provider names for completion
 */
const PROVIDERS = [
  // Global Leaders
  'deepgram', 'google', 'azure', 'openai', 'elevenlabs', 'assemblyai', 'cartesia',
  'amazon', 'ibm', 'groq',
  // European
  'speechmatics', 'gladia', 'revai', 'phonexia', 'acapela', 'cereproc',
  // Russia/CIS
  'yandex', 'tinkoff', 'sberdevices',
  // India
  'sarvam', 'gnani', 'reverie', 'bhashini',
  // China
  'iflytek', 'alibaba', 'baidu', 'tencent', 'huawei',
  // East Asia
  'naver', 'amivoice',
  // Southeast Asia
  'zalo', 'fpt', 'viettel', 'prosa', 'nectec',
  // Voice Cloning
  'hume', 'lmnt', 'playht', 'murf', 'wellsaid', 'resemble', 'speechify', 'unrealspeech', 'smallest',
];

/**
 * Global options for completion (kept for future use)
 */
const _GLOBAL_OPTIONS = [
  { short: '-c', long: '--config', hasArg: true, desc: 'Config file path' },
  { short: '-p', long: '--profile', hasArg: true, desc: 'Configuration profile' },
  { short: '-g', long: '--gateway', hasArg: true, desc: 'Gateway URL override' },
  { short: '', long: '--json', hasArg: false, desc: 'JSON output mode' },
  { short: '-v', long: '--verbose', hasArg: false, desc: 'Verbose logging' },
  { short: '-q', long: '--quiet', hasArg: false, desc: 'Suppress output' },
  { short: '', long: '--no-color', hasArg: false, desc: 'Disable colors' },
  { short: '', long: '--no-animation', hasArg: false, desc: 'Disable animations' },
  { short: '-V', long: '--version', hasArg: false, desc: 'Output version' },
  { short: '-h', long: '--help', hasArg: false, desc: 'Display help' },
];

/**
 * Generate Bash completion script
 */
function generateBashCompletion(): string {
  const commandList = Object.keys(COMMANDS).filter(c => !c.includes(' ')).join(' ');
  const providerList = PROVIDERS.join(' ');

  return `# waav bash completion
# Generated by waav completion bash

_waav_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="${commandList}"
    local providers="${providerList}"

    # Handle subcommands
    case "\${words[1]}" in
        config)
            COMPREPLY=($(compgen -W "show set edit reset" -- "\${cur}"))
            return 0
            ;;
        provider)
            if [[ \${cword} -eq 2 ]]; then
                COMPREPLY=($(compgen -W "list add test browse remove" -- "\${cur}"))
            elif [[ \${cword} -eq 3 && ("\${words[2]}" == "add" || "\${words[2]}" == "test" || "\${words[2]}" == "remove") ]]; then
                COMPREPLY=($(compgen -W "\${providers}" -- "\${cur}"))
            fi
            return 0
            ;;
        dag)
            COMPREPLY=($(compgen -W "list create validate visualize edit" -- "\${cur}"))
            return 0
            ;;
        server)
            COMPREPLY=($(compgen -W "start stop restart status logs" -- "\${cur}"))
            return 0
            ;;
        voice)
            COMPREPLY=($(compgen -W "start test configure" -- "\${cur}"))
            return 0
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh fish powershell" -- "\${cur}"))
            return 0
            ;;
    esac

    # Handle options
    if [[ "\${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "-c --config -p --profile -g --gateway --json -v --verbose -q --quiet --no-color --no-animation -V --version -h --help" -- "\${cur}"))
        return 0
    fi

    # Default to commands
    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
    fi
}

complete -F _waav_completions waav
`;
}

/**
 * Generate Zsh completion script
 */
function generateZshCompletion(): string {
  const providerList = PROVIDERS.map(p => `'${p}:${p} provider'`).join(' ');

  return `#compdef waav
# waav zsh completion
# Generated by waav completion zsh

_waav() {
    local -a commands
    local -a providers

    commands=(
        'init:First-time setup wizard'
        'config:Configuration management'
        'provider:Provider management'
        'dag:DAG pipeline management'
        'server:Gateway server control'
        'voice:Voice interaction mode'
        'dashboard:Interactive analytics dashboard'
        'doctor:Diagnose issues'
        'completion:Generate shell completions'
    )

    providers=(${providerList})

    local -a config_commands
    config_commands=(
        'show:Display current configuration'
        'set:Set configuration value'
        'edit:Open config in editor'
        'reset:Reset to defaults'
    )

    local -a provider_commands
    provider_commands=(
        'list:List all providers'
        'add:Add/configure a provider'
        'test:Test provider connectivity'
        'browse:Interactive provider browser'
        'remove:Remove provider configuration'
    )

    local -a dag_commands
    dag_commands=(
        'list:List saved DAG pipelines'
        'create:Create new DAG pipeline'
        'validate:Validate DAG configuration'
        'visualize:ASCII visualization of DAG'
        'edit:Edit existing DAG'
    )

    local -a server_commands
    server_commands=(
        'start:Start the gateway server'
        'stop:Stop the gateway server'
        'restart:Restart the gateway server'
        'status:Show server status'
        'logs:Tail server logs'
    )

    local -a voice_commands
    voice_commands=(
        'start:Start voice conversation'
        'test:Test mic/speaker setup'
        'configure:Audio device configuration'
    )

    local -a completion_commands
    completion_commands=(
        'bash:Generate bash completion'
        'zsh:Generate zsh completion'
        'fish:Generate fish completion'
        'powershell:Generate PowerShell completion'
    )

    _arguments -C \\
        '-c[Config file path]:config file:_files' \\
        '--config[Config file path]:config file:_files' \\
        '-p[Configuration profile]:profile:' \\
        '--profile[Configuration profile]:profile:' \\
        '-g[Gateway URL override]:url:' \\
        '--gateway[Gateway URL override]:url:' \\
        '--json[JSON output mode]' \\
        '-v[Verbose logging]' \\
        '--verbose[Verbose logging]' \\
        '-q[Suppress output]' \\
        '--quiet[Suppress output]' \\
        '--no-color[Disable colors]' \\
        '--no-animation[Disable animations]' \\
        '-V[Output version]' \\
        '--version[Output version]' \\
        '-h[Display help]' \\
        '--help[Display help]' \\
        '1: :->command' \\
        '2: :->subcommand' \\
        '3: :->arg' \\
        && return 0

    case "$state" in
        command)
            _describe -t commands 'waav command' commands
            ;;
        subcommand)
            case "$words[2]" in
                config)
                    _describe -t config_commands 'config command' config_commands
                    ;;
                provider)
                    _describe -t provider_commands 'provider command' provider_commands
                    ;;
                dag)
                    _describe -t dag_commands 'dag command' dag_commands
                    ;;
                server)
                    _describe -t server_commands 'server command' server_commands
                    ;;
                voice)
                    _describe -t voice_commands 'voice command' voice_commands
                    ;;
                completion)
                    _describe -t completion_commands 'shell' completion_commands
                    ;;
            esac
            ;;
        arg)
            case "$words[2]-$words[3]" in
                provider-add|provider-test|provider-remove)
                    _describe -t providers 'provider' providers
                    ;;
            esac
            ;;
    esac
}

_waav "$@"
`;
}

/**
 * Generate Fish completion script
 */
function generateFishCompletion(): string {
  const commands = [
    'init', 'config', 'provider', 'dag', 'server', 'voice', 'dashboard', 'doctor', 'completion'
  ];

  let script = `# waav fish completion
# Generated by waav completion fish

# Disable file completion by default
complete -c waav -f

# Commands
`;

  for (const cmd of commands) {
    const desc = COMMANDS[cmd as keyof typeof COMMANDS];
    script += `complete -c waav -n "__fish_use_subcommand" -a "${cmd}" -d "${desc}"\n`;
  }

  script += `
# Config subcommands
complete -c waav -n "__fish_seen_subcommand_from config" -a "show" -d "Display current configuration"
complete -c waav -n "__fish_seen_subcommand_from config" -a "set" -d "Set configuration value"
complete -c waav -n "__fish_seen_subcommand_from config" -a "edit" -d "Open config in editor"
complete -c waav -n "__fish_seen_subcommand_from config" -a "reset" -d "Reset to defaults"

# Provider subcommands
complete -c waav -n "__fish_seen_subcommand_from provider" -a "list" -d "List all providers"
complete -c waav -n "__fish_seen_subcommand_from provider" -a "add" -d "Add/configure a provider"
complete -c waav -n "__fish_seen_subcommand_from provider" -a "test" -d "Test provider connectivity"
complete -c waav -n "__fish_seen_subcommand_from provider" -a "browse" -d "Interactive provider browser"
complete -c waav -n "__fish_seen_subcommand_from provider" -a "remove" -d "Remove provider configuration"

# Provider names for add/test/remove
`;

  for (const provider of PROVIDERS) {
    script += `complete -c waav -n "__fish_seen_subcommand_from add test remove" -a "${provider}" -d "${provider} provider"\n`;
  }

  script += `
# DAG subcommands
complete -c waav -n "__fish_seen_subcommand_from dag" -a "list" -d "List saved DAG pipelines"
complete -c waav -n "__fish_seen_subcommand_from dag" -a "create" -d "Create new DAG pipeline"
complete -c waav -n "__fish_seen_subcommand_from dag" -a "validate" -d "Validate DAG configuration"
complete -c waav -n "__fish_seen_subcommand_from dag" -a "visualize" -d "ASCII visualization of DAG"
complete -c waav -n "__fish_seen_subcommand_from dag" -a "edit" -d "Edit existing DAG"

# Server subcommands
complete -c waav -n "__fish_seen_subcommand_from server" -a "start" -d "Start the gateway server"
complete -c waav -n "__fish_seen_subcommand_from server" -a "stop" -d "Stop the gateway server"
complete -c waav -n "__fish_seen_subcommand_from server" -a "restart" -d "Restart the gateway server"
complete -c waav -n "__fish_seen_subcommand_from server" -a "status" -d "Show server status"
complete -c waav -n "__fish_seen_subcommand_from server" -a "logs" -d "Tail server logs"

# Voice subcommands
complete -c waav -n "__fish_seen_subcommand_from voice" -a "start" -d "Start voice conversation"
complete -c waav -n "__fish_seen_subcommand_from voice" -a "test" -d "Test mic/speaker setup"
complete -c waav -n "__fish_seen_subcommand_from voice" -a "configure" -d "Audio device configuration"

# Completion subcommands
complete -c waav -n "__fish_seen_subcommand_from completion" -a "bash" -d "Generate bash completion"
complete -c waav -n "__fish_seen_subcommand_from completion" -a "zsh" -d "Generate zsh completion"
complete -c waav -n "__fish_seen_subcommand_from completion" -a "fish" -d "Generate fish completion"
complete -c waav -n "__fish_seen_subcommand_from completion" -a "powershell" -d "Generate PowerShell completion"

# Global options
complete -c waav -s c -l config -d "Config file path" -r
complete -c waav -s p -l profile -d "Configuration profile" -r
complete -c waav -s g -l gateway -d "Gateway URL override" -r
complete -c waav -l json -d "JSON output mode"
complete -c waav -s v -l verbose -d "Verbose logging"
complete -c waav -s q -l quiet -d "Suppress output"
complete -c waav -l no-color -d "Disable colors"
complete -c waav -l no-animation -d "Disable animations"
complete -c waav -s V -l version -d "Output version"
complete -c waav -s h -l help -d "Display help"
`;

  return script;
}

/**
 * Generate PowerShell completion script
 */
function generatePowerShellCompletion(): string {
  const commands = Object.keys(COMMANDS).filter(c => !c.includes(' '));
  const providerList = PROVIDERS.map(p => `'${p}'`).join(', ');

  return `# waav PowerShell completion
# Generated by waav completion powershell

$script:waavCommands = @('${commands.join("', '")}')
$script:waavProviders = @(${providerList})

$script:waavSubcommands = @{
    'config' = @('show', 'set', 'edit', 'reset')
    'provider' = @('list', 'add', 'test', 'browse', 'remove')
    'dag' = @('list', 'create', 'validate', 'visualize', 'edit')
    'server' = @('start', 'stop', 'restart', 'status', 'logs')
    'voice' = @('start', 'test', 'configure')
    'completion' = @('bash', 'zsh', 'fish', 'powershell')
}

Register-ArgumentCompleter -Native -CommandName waav -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }

    # First argument - commands
    if ($words.Count -eq 1 -or ($words.Count -eq 2 -and $words[1] -eq $wordToComplete)) {
        $script:waavCommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
        return
    }

    # Second argument - subcommands
    $command = $words[1]
    if ($script:waavSubcommands.ContainsKey($command)) {
        if ($words.Count -eq 2 -or ($words.Count -eq 3 -and $words[2] -eq $wordToComplete)) {
            $script:waavSubcommands[$command] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
            return
        }

        # Third argument - provider names for provider add/test/remove
        if ($command -eq 'provider' -and $words[2] -in @('add', 'test', 'remove')) {
            $script:waavProviders | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
            return
        }
    }

    # Options
    if ($wordToComplete -like '-*') {
        @(
            @{Name = '-c'; Tooltip = 'Config file path'},
            @{Name = '--config'; Tooltip = 'Config file path'},
            @{Name = '-p'; Tooltip = 'Configuration profile'},
            @{Name = '--profile'; Tooltip = 'Configuration profile'},
            @{Name = '-g'; Tooltip = 'Gateway URL override'},
            @{Name = '--gateway'; Tooltip = 'Gateway URL override'},
            @{Name = '--json'; Tooltip = 'JSON output mode'},
            @{Name = '-v'; Tooltip = 'Verbose logging'},
            @{Name = '--verbose'; Tooltip = 'Verbose logging'},
            @{Name = '-q'; Tooltip = 'Suppress output'},
            @{Name = '--quiet'; Tooltip = 'Suppress output'},
            @{Name = '--no-color'; Tooltip = 'Disable colors'},
            @{Name = '--no-animation'; Tooltip = 'Disable animations'},
            @{Name = '-V'; Tooltip = 'Output version'},
            @{Name = '--version'; Tooltip = 'Output version'},
            @{Name = '-h'; Tooltip = 'Display help'},
            @{Name = '--help'; Tooltip = 'Display help'}
        ) | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterName', $_.Tooltip)
        }
    }
}
`;
}

/**
 * Completion command handler
 */
export async function completionCommand(shell: string, _options: GlobalOptions): Promise<void> {
  const normalizedShell = shell.toLowerCase() as Shell;

  switch (normalizedShell) {
    case 'bash':
      console.log(generateBashCompletion());
      break;
    case 'zsh':
      console.log(generateZshCompletion());
      break;
    case 'fish':
      console.log(generateFishCompletion());
      break;
    case 'powershell':
      console.log(generatePowerShellCompletion());
      break;
    default:
      logger.error(`Unknown shell: ${shell}`);
      logger.info('Supported shells: bash, zsh, fish, powershell');
      logger.plain('');
      logger.plain('Usage:');
      logger.plain('  waav completion bash > ~/.bash_completion.d/waav');
      logger.plain('  waav completion zsh > ~/.zfunc/_waav');
      logger.plain('  waav completion fish > ~/.config/fish/completions/waav.fish');
      logger.plain('  waav completion powershell >> $PROFILE');
      process.exitCode = 1;
  }
}

export default completionCommand;
