//! ElevenLabs Conversational AI ("ConvAI") [`RealtimeProtocol`] — a base64+JSON
//! speech-to-speech provider (the OpenAI-family wire shape, NOT Deepgram's raw
//! binary). ConvAI runs the whole STT→LLM→TTS loop server-side against a
//! PRE-CREATED *agent* (the agent IS the model): server VAD, turn-taking, and
//! barge-in are all owned by ElevenLabs.
//!
//! Wire (banked from a LIVE probe + the ElevenLabs ConvAI WebSocket docs):
//! - Connect: `wss://api.elevenlabs.io/v1/convai/conversation?agent_id=<id>`,
//!   header `xi-api-key: <key>`. The `agent_id` is read from `cfg.model`.
//! - Audio: `pcm_16000` BOTH directions (16 kHz mono 16-bit ⇒ 32 B/ms).
//! - All frames are JSON; user audio is base64 INSIDE a JSON event
//!   (`{"user_audio_chunk": base64(pcm)}`), so `Wire = serde_json::Value` and
//!   every message serializes to `OutFrame::Text`.
//! - APP-level keepalive: the server sends `{"type":"ping",...}` and the client
//!   must reply `{"type":"pong","event_id":N}`. This is NOT a WS-protocol ping
//!   (the transport's Ping/Pong does not cover it), so it is lowered to
//!   [`S2sEvent::SendFrame`] — the driver sends it on the outbound path.
//!
//! Docs: <https://elevenlabs.io/docs/conversational-ai/api-reference/conversational-ai/websocket>

use base64::prelude::*;
use bytes::Bytes;
use serde_json::{json, Value};

use crate::core::realtime::base::{
    FunctionCallRequest, RealtimeConfig, RealtimeError, RealtimeResponseOverride, RealtimeResult,
    TranscriptRole,
};
use crate::core::realtime::scaffold::{
    ConnectSpec, Inbound, OutFrame, ProtocolCaps, RealtimeProtocol, S2sEvent,
};

/// ElevenLabs ConvAI WebSocket base endpoint. The `agent_id` query is appended
/// in `connect_spec`. LIVE-probed working endpoint.
pub(crate) const ELEVENLABS_CONVAI_URL: &str =
    "wss://api.elevenlabs.io/v1/convai/conversation";

/// ConvAI uses `pcm_16000` both directions: 16 kHz mono 16-bit ⇒ 2 B/sample ×
/// 16 samples/ms = 32 B/ms.
const OUTPUT_BYTES_PER_MS: u64 = 32;
/// Output sample rate stamped onto delivered audio.
const OUTPUT_SAMPLE_RATE: u32 = 16_000;

/// The ElevenLabs ConvAI protocol. Stateless: the only provider-specific config
/// the wire mappings need is the pre-created agent id (`cfg.model`) and the api
/// key (re-read from `cfg` in `connect_spec`), so it carries nothing but what
/// `from_config` validated.
pub struct ElevenLabsProtocol {
    /// The pre-created ConvAI agent id (the "model"); embedded in the connect
    /// query. Validated non-empty at `from_config`.
    agent_id: String,
}

impl ElevenLabsProtocol {
    /// Resolve the agent id: `cfg.model` is canonical (the ConvAI agent IS the
    /// model); `cfg.endpoint` is a documented fallback carrier.
    fn resolve_agent_id(cfg: &RealtimeConfig) -> String {
        let model = cfg.model.trim();
        if !model.is_empty() {
            return model.to_string();
        }
        cfg.endpoint
            .as_deref()
            .map(str::trim)
            .unwrap_or("")
            .to_string()
    }
}

impl RealtimeProtocol for ElevenLabsProtocol {
    type Wire = Value;

    fn from_config(cfg: &RealtimeConfig) -> RealtimeResult<Self> {
        // ConvAI auths with `xi-api-key: <key>` — a non-empty key is required.
        if cfg.api_key.is_empty() {
            return Err(RealtimeError::AuthenticationFailed(
                "API key is required".to_string(),
            ));
        }
        // ConvAI needs a PRE-CREATED agent_id (the agent IS the model).
        let agent_id = Self::resolve_agent_id(cfg);
        if agent_id.is_empty() {
            return Err(RealtimeError::InvalidConfiguration(
                "ElevenLabs ConvAI requires an agent_id in `model`".to_string(),
            ));
        }
        Ok(Self { agent_id })
    }

    fn provider_id(&self) -> &'static str {
        "elevenlabs"
    }

    fn caps(&self) -> ProtocolCaps {
        ProtocolCaps {
            // ConvAI runs server-side VAD + turn-taking, so it owns turns and
            // emits user-turn frames (user_transcript, interruption).
            emits_user_turn_frames: true,
            output_bytes_per_ms: OUTPUT_BYTES_PER_MS,
            output_sample_rate: OUTPUT_SAMPLE_RATE,
            // ConvAI has no client-driven item truncation (barge-in is server-side
            // via `interruption`; the driver only clears local playback).
            supports_truncate: false,
            // No gateway-managed input buffer (audio is streamed as JSON chunks).
            supports_input_buffer: false,
        }
    }

    fn connect_spec(&self, cfg: &RealtimeConfig) -> RealtimeResult<ConnectSpec> {
        // `agent_id` in the query; `xi-api-key` header (NOT Bearer). The standard
        // WS-upgrade headers are generated by `into_client_request()` in the
        // transport factory.
        Ok(ConnectSpec::WebSocket {
            url: format!("{ELEVENLABS_CONVAI_URL}?agent_id={}", self.agent_id),
            headers: vec![("xi-api-key".to_string(), cfg.api_key.clone())],
        })
    }

    fn build_session_config(
        &self,
        cfg: &RealtimeConfig,
        _resumption: Option<&str>,
    ) -> Vec<Self::Wire> {
        // The agent's own (pre-created) configuration applies by default. Only
        // emit `conversation_initiation_client_data` when we actually have an
        // instructions override (skip-if-none discipline) — an empty vec means
        // "use the agent's config verbatim".
        match cfg.instructions.as_deref() {
            Some(instr) if !instr.is_empty() => vec![json!({
                "type": "conversation_initiation_client_data",
                "conversation_config_override": {
                    "agent": { "prompt": { "prompt": instr } },
                },
            })],
            _ => Vec::new(),
        }
    }

    fn map_server_event(&self, raw: Inbound<'_>) -> Vec<S2sEvent> {
        // ConvAI is JSON-only; a binary frame is never expected.
        let text = match raw {
            Inbound::Text(t) => t,
            Inbound::Binary(_) => return vec![S2sEvent::Ignore],
        };

        let value: Value = match serde_json::from_str(text) {
            Ok(v) => v,
            Err(_) => return vec![S2sEvent::Ignore],
        };
        let msg_type = value.get("type").and_then(Value::as_str).unwrap_or("");

        match msg_type {
            // Session ack: carries the ConvAI conversation_id.
            // `{"type":"conversation_initiation_metadata",
            //   "conversation_initiation_metadata_event":{"conversation_id":"…",…}}`
            "conversation_initiation_metadata" => vec![S2sEvent::SessionReady {
                session_id: value
                    .get("conversation_initiation_metadata_event")
                    .and_then(|e| e.get("conversation_id"))
                    .and_then(Value::as_str)
                    .map(str::to_string),
            }],
            // FINAL user transcript:
            // `{"type":"user_transcript",
            //   "user_transcription_event":{"user_transcript":"…"}}`
            "user_transcript" => {
                let text = value
                    .get("user_transcription_event")
                    .and_then(|e| e.get("user_transcript"))
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                vec![S2sEvent::Transcript {
                    role: TranscriptRole::User,
                    text,
                    is_final: true,
                    item_id: None,
                }]
            }
            // FINAL agent response (assistant text):
            // `{"type":"agent_response",
            //   "agent_response_event":{"agent_response":"…"}}`
            "agent_response" => {
                let text = value
                    .get("agent_response_event")
                    .and_then(|e| e.get("agent_response"))
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                vec![S2sEvent::Transcript {
                    role: TranscriptRole::Assistant,
                    text,
                    is_final: true,
                    item_id: None,
                }]
            }
            // Agent TTS audio (base64'd PCM16 @ 16 kHz):
            // `{"type":"audio","audio_event":{"audio_base_64":"…","event_id":N}}`
            "audio" => {
                let b64 = value
                    .get("audio_event")
                    .and_then(|e| e.get("audio_base_64"))
                    .and_then(Value::as_str)
                    .unwrap_or("");
                match BASE64_STANDARD.decode(b64) {
                    Ok(bytes) => vec![S2sEvent::Audio {
                        data: Bytes::from(bytes),
                        item_id: None,
                        response_id: None,
                    }],
                    Err(_) => vec![S2sEvent::Ignore],
                }
            }
            // Barge-in: the user interrupted; the server already stopped agent
            // audio. The driver clears local playback (NO truncate — ConvAI has
            // none). `{"type":"interruption","interruption_event":{…}}`
            "interruption" => vec![S2sEvent::InterruptedByServer],
            // APP-level keepalive: server `ping` → client `pong` echoing the
            // event_id. NOT a WS-protocol ping, so it is lowered to a SendFrame
            // (the driver routes it to the transport). THE Task-A SendFrame use.
            // `{"type":"ping","ping_event":{"event_id":N,"ping_ms":M}}`
            "ping" => {
                let event_id = value
                    .get("ping_event")
                    .and_then(|e| e.get("event_id"))
                    .cloned()
                    .unwrap_or(Value::Null);
                let pong = json!({ "type": "pong", "event_id": event_id });
                vec![S2sEvent::SendFrame(OutFrame::Text(pong.to_string()))]
            }
            // A correction supersedes a prior agent_response. Ignore to avoid
            // double-logging the assistant turn (the original already logged).
            "agent_response_correction" => vec![S2sEvent::Ignore],
            // Client-side tool call:
            // `{"type":"client_tool_call",
            //   "client_tool_call":{"tool_name","tool_call_id","parameters"}}`
            "client_tool_call" => {
                let call = value.get("client_tool_call");
                let tool_call_id = call
                    .and_then(|c| c.get("tool_call_id"))
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                let tool_name = call
                    .and_then(|c| c.get("tool_name"))
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                // `parameters` is a JSON object; stringify it for the generic
                // FunctionCallRequest.arguments (a JSON string).
                let arguments = call
                    .and_then(|c| c.get("parameters"))
                    .map(|p| p.to_string())
                    .unwrap_or_else(|| "{}".to_string());
                vec![S2sEvent::FunctionCall(FunctionCallRequest {
                    call_id: tool_call_id,
                    name: tool_name,
                    arguments,
                    item_id: None,
                })]
            }
            // VAD scores + any unknown event ⇒ nothing actionable.
            _ => vec![S2sEvent::Ignore],
        }
    }

    fn encode_user_audio(&self, pcm: &[u8]) -> Self::Wire {
        // base64-in-JSON (NOT raw binary): `{"user_audio_chunk": base64(pcm)}`.
        json!({ "user_audio_chunk": BASE64_STANDARD.encode(pcm) })
    }

    fn send_text(&self, text: &str) -> Vec<Self::Wire> {
        // ConvAI text input (per docs): `{"type":"user_message","text":"…"}`.
        // Best-effort — the primary modality is audio; this lets a client inject
        // a typed user turn.
        vec![json!({ "type": "user_message", "text": text })]
    }

    fn create_response(&self, _overrides: Option<&RealtimeResponseOverride>) -> Vec<Self::Wire> {
        // Server VAD + turn-taking owns response creation; nothing to send.
        Vec::new()
    }

    fn commit_turn(&self) -> Vec<Self::Wire> {
        // Server VAD owns turn close.
        Vec::new()
    }

    fn cancel_response(&self) -> Vec<Self::Wire> {
        // ConvAI has no client-driven response cancel; barge-in is server-side
        // (`interruption`). Safest to send nothing.
        Vec::new()
    }

    fn format_tool_result(&self, call_id: &str, result: &str) -> Vec<Self::Wire> {
        // Tool result → `client_tool_result` (per docs): echo the tool_call_id,
        // carry the result, and flag success.
        vec![json!({
            "type": "client_tool_result",
            "tool_call_id": call_id,
            "result": result,
            "is_error": false,
        })]
    }

    fn serialize(&self, msg: &Self::Wire) -> RealtimeResult<OutFrame> {
        // ConvAI is JSON-only (audio is base64 inside JSON) ⇒ ALWAYS a text frame.
        Ok(OutFrame::Text(serde_json::to_string(msg).map_err(|e| {
            RealtimeError::SerializationError(e.to_string())
        })?))
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn base_cfg() -> RealtimeConfig {
        RealtimeConfig {
            provider: "elevenlabs".into(),
            api_key: "xikey".into(),
            model: "agent_abc123".into(),
            ..Default::default()
        }
    }

    fn proto(cfg: &RealtimeConfig) -> ElevenLabsProtocol {
        ElevenLabsProtocol::from_config(cfg).unwrap()
    }

    /// from_config rejects an empty api key (`xi-api-key` auth requires it).
    #[test]
    fn from_config_requires_api_key() {
        let cfg = RealtimeConfig {
            api_key: String::new(),
            model: "agent_abc123".into(),
            ..Default::default()
        };
        assert!(matches!(
            ElevenLabsProtocol::from_config(&cfg),
            Err(RealtimeError::AuthenticationFailed(_))
        ));
    }

    /// from_config rejects an empty agent_id (ConvAI needs a pre-created agent).
    #[test]
    fn from_config_requires_agent_id() {
        let cfg = RealtimeConfig {
            api_key: "xikey".into(),
            model: String::new(),
            ..Default::default()
        };
        match ElevenLabsProtocol::from_config(&cfg) {
            Err(RealtimeError::InvalidConfiguration(msg)) => {
                assert!(msg.contains("agent_id"), "msg should name agent_id: {msg}");
            }
            Err(other) => panic!("expected InvalidConfiguration, got {other:?}"),
            Ok(_) => panic!("expected InvalidConfiguration for an empty agent_id"),
        }
    }

    /// from_config accepts the agent_id via the `endpoint` fallback when `model`
    /// is empty.
    #[test]
    fn from_config_agent_id_endpoint_fallback() {
        let cfg = RealtimeConfig {
            api_key: "xikey".into(),
            model: String::new(),
            endpoint: Some("agent_from_endpoint".into()),
            ..Default::default()
        };
        let p = ElevenLabsProtocol::from_config(&cfg).unwrap();
        let ConnectSpec::WebSocket { url, .. } = p.connect_spec(&cfg).unwrap() else {
            panic!("expected ConnectSpec::WebSocket")
        };
        assert!(url.contains("agent_id=agent_from_endpoint"));
    }

    /// connect_spec: EXACT ConvAI URL with the agent_id query + `xi-api-key`.
    #[test]
    fn connect_spec_uses_convai_url_and_xi_api_key() {
        let p = proto(&base_cfg());
        let ConnectSpec::WebSocket { url, headers } = p.connect_spec(&base_cfg()).unwrap() else {
            panic!("expected ConnectSpec::WebSocket")
        };
        assert_eq!(
            url,
            "wss://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_abc123"
        );
        let key = headers
            .iter()
            .find(|(k, _)| k == "xi-api-key")
            .map(|(_, v)| v.as_str())
            .expect("xi-api-key header present");
        assert_eq!(key, "xikey");
        // NOT a Bearer Authorization header.
        assert!(!headers.iter().any(|(k, _)| k == "Authorization"));
    }

    /// caps: server-VAD turn frames, 32 B/ms @ 16 kHz, NO truncate, NO input buffer.
    #[test]
    fn caps_describe_server_vad_pcm16k_provider() {
        let c = proto(&base_cfg()).caps();
        assert!(c.emits_user_turn_frames);
        assert_eq!(c.output_bytes_per_ms, 32);
        assert_eq!(c.output_sample_rate, 16_000);
        assert!(!c.supports_truncate);
        assert!(!c.supports_input_buffer);
    }

    /// build_session_config: instructions ⇒ a conversation_initiation_client_data
    /// override; no instructions ⇒ EMPTY (the agent's own config applies).
    #[test]
    fn build_session_config_override_or_empty() {
        // No instructions ⇒ empty.
        assert!(proto(&base_cfg()).build_session_config(&base_cfg(), None).is_empty());
        // Instructions ⇒ one init message carrying the prompt override.
        let cfg = RealtimeConfig {
            instructions: Some("Be terse.".into()),
            ..base_cfg()
        };
        let p = proto(&cfg);
        let wires = p.build_session_config(&cfg, None);
        assert_eq!(wires.len(), 1);
        let v = &wires[0];
        assert_eq!(v["type"], "conversation_initiation_client_data");
        assert_eq!(
            v["conversation_config_override"]["agent"]["prompt"]["prompt"],
            "Be terse."
        );
    }

    /// encode_user_audio ⇒ `{"user_audio_chunk": base64(pcm)}` (base64, NOT raw).
    #[test]
    fn encode_user_audio_is_base64_in_json() {
        let p = proto(&base_cfg());
        let pcm: Vec<u8> = vec![0x00, 0x01, 0xFE, 0xFF, 0x7F, 0x80];
        let wire = p.encode_user_audio(&pcm);
        let b64 = wire["user_audio_chunk"].as_str().expect("user_audio_chunk");
        assert_eq!(BASE64_STANDARD.decode(b64).unwrap(), pcm, "base64 round-trips");
        // And it serializes to a TEXT frame (JSON), never binary.
        match p.serialize(&wire).unwrap() {
            OutFrame::Text(s) => assert!(s.contains("user_audio_chunk")),
            OutFrame::Binary(_) => panic!("ConvAI audio must be a JSON text frame"),
        }
    }

    /// map_server_event: conversation_initiation_metadata ⇒ SessionReady carrying
    /// the conversation_id.
    #[test]
    fn metadata_maps_to_session_ready() {
        let p = proto(&base_cfg());
        let raw = r#"{"type":"conversation_initiation_metadata","conversation_initiation_metadata_event":{"conversation_id":"conv_xyz","agent_output_audio_format":"pcm_16000"}}"#;
        match p.map_server_event(Inbound::Text(raw)).as_slice() {
            [S2sEvent::SessionReady { session_id }] => {
                assert_eq!(session_id.as_deref(), Some("conv_xyz"));
            }
            other => panic!("expected SessionReady, got {other:?}"),
        }
    }

    /// map_server_event: user_transcript ⇒ FINAL user Transcript;
    /// agent_response ⇒ FINAL assistant Transcript.
    #[test]
    fn transcripts_map_per_role() {
        let p = proto(&base_cfg());
        let user = r#"{"type":"user_transcript","user_transcription_event":{"user_transcript":"hello there"}}"#;
        match p.map_server_event(Inbound::Text(user)).as_slice() {
            [S2sEvent::Transcript {
                role,
                text,
                is_final,
                item_id,
            }] => {
                assert_eq!(*role, TranscriptRole::User);
                assert_eq!(text, "hello there");
                assert!(*is_final);
                assert!(item_id.is_none());
            }
            other => panic!("expected user Transcript, got {other:?}"),
        }
        let asst = r#"{"type":"agent_response","agent_response_event":{"agent_response":"hi!"}}"#;
        match p.map_server_event(Inbound::Text(asst)).as_slice() {
            [S2sEvent::Transcript {
                role,
                text,
                is_final,
                ..
            }] => {
                assert_eq!(*role, TranscriptRole::Assistant);
                assert_eq!(text, "hi!");
                assert!(*is_final);
            }
            other => panic!("expected assistant Transcript, got {other:?}"),
        }
    }

    /// map_server_event: audio ⇒ Audio with the base64-DECODED PCM bytes.
    #[test]
    fn audio_maps_to_decoded_audio() {
        let p = proto(&base_cfg());
        let pcm: &[u8] = &[1, 2, 3, 4, 250, 251];
        let b64 = BASE64_STANDARD.encode(pcm);
        let raw = format!(
            r#"{{"type":"audio","audio_event":{{"audio_base_64":"{b64}","event_id":7}}}}"#
        );
        match p.map_server_event(Inbound::Text(&raw)).as_slice() {
            [S2sEvent::Audio {
                data,
                item_id,
                response_id,
            }] => {
                assert_eq!(data.as_ref(), pcm, "audio is base64-decoded");
                assert!(item_id.is_none());
                assert!(response_id.is_none());
            }
            other => panic!("expected Audio, got {other:?}"),
        }
    }

    /// map_server_event: interruption ⇒ InterruptedByServer (server barge-in).
    #[test]
    fn interruption_maps_to_interrupted_by_server() {
        let p = proto(&base_cfg());
        let raw = r#"{"type":"interruption","interruption_event":{"reason":"agent_interrupted"}}"#;
        assert!(matches!(
            p.map_server_event(Inbound::Text(raw)).as_slice(),
            [S2sEvent::InterruptedByServer]
        ));
    }

    /// THE Task-A SendFrame mapping: ping ⇒ SendFrame(pong) echoing the EXACT
    /// event_id, as a JSON text frame.
    #[test]
    fn ping_maps_to_send_frame_pong_with_event_id() {
        let p = proto(&base_cfg());
        let raw = r#"{"type":"ping","ping_event":{"event_id":42,"ping_ms":1500}}"#;
        match p.map_server_event(Inbound::Text(raw)).as_slice() {
            [S2sEvent::SendFrame(OutFrame::Text(s))] => {
                let v: Value = serde_json::from_str(s).unwrap();
                assert_eq!(v["type"], "pong");
                assert_eq!(v["event_id"], 42, "pong must echo the ping event_id");
            }
            other => panic!("expected SendFrame(pong), got {other:?}"),
        }
    }

    /// map_server_event: client_tool_call ⇒ FunctionCall with id/name/parameters.
    #[test]
    fn client_tool_call_maps_to_function_call() {
        let p = proto(&base_cfg());
        let raw = r#"{"type":"client_tool_call","client_tool_call":{"tool_name":"get_weather","tool_call_id":"call_1","parameters":{"city":"NYC"}}}"#;
        match p.map_server_event(Inbound::Text(raw)).as_slice() {
            [S2sEvent::FunctionCall(req)] => {
                assert_eq!(req.call_id, "call_1");
                assert_eq!(req.name, "get_weather");
                // arguments is the stringified parameters object.
                let args: Value = serde_json::from_str(&req.arguments).unwrap();
                assert_eq!(args["city"], "NYC");
                assert!(req.item_id.is_none());
            }
            other => panic!("expected FunctionCall, got {other:?}"),
        }
    }

    /// map_server_event: agent_response_correction ⇒ Ignore (avoid double-log);
    /// vad_score / unknown ⇒ Ignore; a BINARY inbound ⇒ Ignore (ConvAI is JSON).
    #[test]
    fn correction_vad_unknown_and_binary_ignore() {
        let p = proto(&base_cfg());
        let correction = r#"{"type":"agent_response_correction","agent_response_correction_event":{"corrected_agent_response":"x"}}"#;
        assert!(matches!(
            p.map_server_event(Inbound::Text(correction)).as_slice(),
            [S2sEvent::Ignore]
        ));
        assert!(matches!(
            p.map_server_event(Inbound::Text(r#"{"type":"vad_score","vad_score_event":{"vad_score":0.9}}"#))
                .as_slice(),
            [S2sEvent::Ignore]
        ));
        assert!(matches!(
            p.map_server_event(Inbound::Text(r#"{"type":"something_new"}"#))
                .as_slice(),
            [S2sEvent::Ignore]
        ));
        assert!(matches!(
            p.map_server_event(Inbound::Text("not json")).as_slice(),
            [S2sEvent::Ignore]
        ));
        assert!(matches!(
            p.map_server_event(Inbound::Binary(&[1, 2, 3])).as_slice(),
            [S2sEvent::Ignore]
        ));
    }

    /// send_text ⇒ user_message; format_tool_result ⇒ client_tool_result;
    /// turn/cancel controls are empty (server VAD owns them).
    #[test]
    fn send_text_tool_result_and_empty_turn_controls() {
        let p = proto(&base_cfg());
        match p.send_text("typed turn").as_slice() {
            [v] => {
                assert_eq!(v["type"], "user_message");
                assert_eq!(v["text"], "typed turn");
            }
            other => panic!("expected one user_message, got {other:?}"),
        }
        match p.format_tool_result("call_1", "72F sunny").as_slice() {
            [v] => {
                assert_eq!(v["type"], "client_tool_result");
                assert_eq!(v["tool_call_id"], "call_1");
                assert_eq!(v["result"], "72F sunny");
                assert_eq!(v["is_error"], false);
            }
            other => panic!("expected client_tool_result, got {other:?}"),
        }
        // Server VAD owns turns: create/commit/cancel all empty.
        assert!(p.create_response(None).is_empty());
        assert!(p.commit_turn().is_empty());
        assert!(p.cancel_response().is_empty());
        // Default-empty truncate / input-buffer / replay (provider lacks them).
        assert!(p.truncate("x", 1).is_empty());
        assert!(p.clear_input_buffer().is_empty());
    }
}
